import type { CareRoutine, Dog } from './types';

export const XP_PER_LEVEL = 150;
export const MAX_LEVEL = 999;

/** Каталог за замовчуванням під Балу. Все редаговане — це дані, не код. Спека §7. */
export const DEFAULT_ROUTINES: CareRoutine[] = [
  {
    id: 'feed',
    title: 'Годування',
    kind: 'slotted',
    group: 'daily',
    xp: 20,
    enabled: true,
    icon: 'bowl',
    perDay: 2,
  },
  {
    id: 'patrol',
    title: 'Патруль',
    kind: 'slotted',
    group: 'daily',
    xp: 30,
    enabled: true,
    icon: 'leash',
    perDay: 3,
  },
  {
    id: 'run',
    title: 'Вільний біг',
    kind: 'quota',
    group: 'journey',
    xp: 100,
    enabled: true,
    icon: 'paw',
    quotaCount: 2,
    quotaPeriod: 'week',
    hint: 'Біг без поводка. Не те саме, що патруль.',
  },
  {
    id: 'fangs',
    title: 'Ікла',
    kind: 'quota',
    group: 'daily',
    xp: 40,
    enabled: true,
    icon: 'fang',
    quotaCount: 3,
    quotaPeriod: 'week',
  },
  {
    id: 'fleas',
    title: 'Зілля від кровопивць',
    kind: 'ward',
    group: 'rite',
    xp: 1200,
    enabled: true,
    icon: 'ward-blood',
    wardDays: 30,
    hint: 'Кліщі й блохи. Упаковка для ваги 10–20 кг.',
  },
  {
    id: 'worms',
    title: 'Зілля від хробаків',
    kind: 'ward',
    group: 'rite',
    xp: 2000,
    enabled: true,
    icon: 'ward-worm',
    wardDays: 90,
    hint: 'Періодичність виставляється за порадою лікаря.',
  },
  {
    id: 'healer',
    title: 'Огляд Цілителя',
    kind: 'duty',
    group: 'rite',
    xp: 4000,
    enabled: true,
    icon: 'healer',
    everyMonths: 6,
    calendarBackup: true,
  },
  {
    id: 'vaccine',
    title: 'Вакцинація',
    kind: 'duty',
    group: 'rite',
    xp: 6000,
    enabled: true,
    icon: 'vial',
    everyMonths: 12,
    calendarBackup: true,
  },
  {
    id: 'weigh',
    title: 'Зважування',
    kind: 'duty',
    group: 'rite',
    xp: 600,
    enabled: true,
    icon: 'scale',
    everyMonths: 1,
  },
  {
    id: 'claws',
    title: 'Кігті',
    kind: 'duty',
    group: 'rite',
    xp: 400,
    enabled: true,
    icon: 'claw',
    everyMonths: 1,
  },
  {
    id: 'forest',
    title: 'Похід у Глибокий Ліс',
    kind: 'quota',
    group: 'journey',
    xp: 2500,
    enabled: true,
    icon: 'tree',
    quotaCount: 1,
    quotaPeriod: 'month',
  },
  {
    id: 'tickcheck',
    title: 'Огляд на кліщів',
    kind: 'spawned',
    group: 'journey',
    xp: 400,
    enabled: true,
    icon: 'eye',
    spawnedBy: 'forest',
    spawnWindowHours: 24,
    hint: 'На чорній короткій шерсті кліща майже не видно.',
  },
];

export const BALU: Dog = {
  id: 'balu',
  name: 'Балу',
  bornAt: Date.UTC(2022, 0, 1),
  breedNote: 'Безпорідний, тип бігового віппета',
  targetWeightMin: 10.5,
  targetWeightMax: 12.5,
  sprites: {},
  palette: ['#2b3040', '#6b7a99', '#d9a54a'],
};
